#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_FOOD.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SFOOD")]
	public partial class DBSfoodDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertVIP(VIP instance);
    partial void UpdateVIP(VIP instance);
    partial void DeleteVIP(VIP instance);
    partial void InsertCAIDAT(CAIDAT instance);
    partial void UpdateCAIDAT(CAIDAT instance);
    partial void DeleteCAIDAT(CAIDAT instance);
    partial void InsertCHIECKHAU(CHIECKHAU instance);
    partial void UpdateCHIECKHAU(CHIECKHAU instance);
    partial void DeleteCHIECKHAU(CHIECKHAU instance);
    partial void InsertCONGTACVIEN(CONGTACVIEN instance);
    partial void UpdateCONGTACVIEN(CONGTACVIEN instance);
    partial void DeleteCONGTACVIEN(CONGTACVIEN instance);
    partial void InsertDATHANG(DATHANG instance);
    partial void UpdateDATHANG(DATHANG instance);
    partial void DeleteDATHANG(DATHANG instance);
    partial void InsertDONHANG(DONHANG instance);
    partial void UpdateDONHANG(DONHANG instance);
    partial void DeleteDONHANG(DONHANG instance);
    partial void InsertKHUVUC(KHUVUC instance);
    partial void UpdateKHUVUC(KHUVUC instance);
    partial void DeleteKHUVUC(KHUVUC instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    partial void InsertLOAIBUAAN(LOAIBUAAN instance);
    partial void UpdateLOAIBUAAN(LOAIBUAAN instance);
    partial void DeleteLOAIBUAAN(LOAIBUAAN instance);
    partial void InsertMONAN(MONAN instance);
    partial void UpdateMONAN(MONAN instance);
    partial void DeleteMONAN(MONAN instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertDOANHTHU(DOANHTHU instance);
    partial void UpdateDOANHTHU(DOANHTHU instance);
    partial void DeleteDOANHTHU(DOANHTHU instance);
    #endregion
		
		public DBSfoodDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SFOODConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBSfoodDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSfoodDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSfoodDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSfoodDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<VIP> VIPs
		{
			get
			{
				return this.GetTable<VIP>();
			}
		}
		
		public System.Data.Linq.Table<CAIDAT> CAIDATs
		{
			get
			{
				return this.GetTable<CAIDAT>();
			}
		}
		
		public System.Data.Linq.Table<CHIECKHAU> CHIECKHAUs
		{
			get
			{
				return this.GetTable<CHIECKHAU>();
			}
		}
		
		public System.Data.Linq.Table<CONGTACVIEN> CONGTACVIENs
		{
			get
			{
				return this.GetTable<CONGTACVIEN>();
			}
		}
		
		public System.Data.Linq.Table<DATHANG> DATHANGs
		{
			get
			{
				return this.GetTable<DATHANG>();
			}
		}
		
		public System.Data.Linq.Table<DONHANG> DONHANGs
		{
			get
			{
				return this.GetTable<DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHUVUC> KHUVUCs
		{
			get
			{
				return this.GetTable<KHUVUC>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<LOAIBUAAN> LOAIBUAANs
		{
			get
			{
				return this.GetTable<LOAIBUAAN>();
			}
		}
		
		public System.Data.Linq.Table<MONAN> MONANs
		{
			get
			{
				return this.GetTable<MONAN>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<V_Top5MonAn> V_Top5MonAns
		{
			get
			{
				return this.GetTable<V_Top5MonAn>();
			}
		}
		
		public System.Data.Linq.Table<V_Top5KhachHang> V_Top5KhachHangs
		{
			get
			{
				return this.GetTable<V_Top5KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DOANHTHU> DOANHTHUs
		{
			get
			{
				return this.GetTable<DOANHTHU>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_UpdateCaiDat")]
		public int p_UpdateCaiDat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenThamSo", DbType="VarChar(50)")] string tenThamSo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTri", DbType="NVarChar(100)")] string giaTri)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenThamSo, giaTri);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.f_tongdt", IsComposable=true)]
		public System.Nullable<decimal> f_tongdt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idctv)
		{
			return ((System.Nullable<decimal>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idctv).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK_Admin;
		
		private string _TenTK_Admin;
		
		private string _MatKhau_Admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTK_AdminChanging(int value);
    partial void OnMaTK_AdminChanged();
    partial void OnTenTK_AdminChanging(string value);
    partial void OnTenTK_AdminChanged();
    partial void OnMatKhau_AdminChanging(string value);
    partial void OnMatKhau_AdminChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_Admin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTK_Admin
		{
			get
			{
				return this._MaTK_Admin;
			}
			set
			{
				if ((this._MaTK_Admin != value))
				{
					this.OnMaTK_AdminChanging(value);
					this.SendPropertyChanging();
					this._MaTK_Admin = value;
					this.SendPropertyChanged("MaTK_Admin");
					this.OnMaTK_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK_Admin", DbType="VarChar(30)")]
		public string TenTK_Admin
		{
			get
			{
				return this._TenTK_Admin;
			}
			set
			{
				if ((this._TenTK_Admin != value))
				{
					this.OnTenTK_AdminChanging(value);
					this.SendPropertyChanging();
					this._TenTK_Admin = value;
					this.SendPropertyChanged("TenTK_Admin");
					this.OnTenTK_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau_Admin", DbType="VarChar(30)")]
		public string MatKhau_Admin
		{
			get
			{
				return this._MatKhau_Admin;
			}
			set
			{
				if ((this._MatKhau_Admin != value))
				{
					this.OnMatKhau_AdminChanging(value);
					this.SendPropertyChanging();
					this._MatKhau_Admin = value;
					this.SendPropertyChanged("MatKhau_Admin");
					this.OnMatKhau_AdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIP")]
	public partial class VIP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LevelVip;
		
		private System.Nullable<decimal> _SoTienCanTra;
		
		private EntitySet<CONGTACVIEN> _CONGTACVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLevelVipChanging(int value);
    partial void OnLevelVipChanged();
    partial void OnSoTienCanTraChanging(System.Nullable<decimal> value);
    partial void OnSoTienCanTraChanged();
    #endregion
		
		public VIP()
		{
			this._CONGTACVIENs = new EntitySet<CONGTACVIEN>(new Action<CONGTACVIEN>(this.attach_CONGTACVIENs), new Action<CONGTACVIEN>(this.detach_CONGTACVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelVip", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LevelVip
		{
			get
			{
				return this._LevelVip;
			}
			set
			{
				if ((this._LevelVip != value))
				{
					this.OnLevelVipChanging(value);
					this.SendPropertyChanging();
					this._LevelVip = value;
					this.SendPropertyChanged("LevelVip");
					this.OnLevelVipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienCanTra", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> SoTienCanTra
		{
			get
			{
				return this._SoTienCanTra;
			}
			set
			{
				if ((this._SoTienCanTra != value))
				{
					this.OnSoTienCanTraChanging(value);
					this.SendPropertyChanging();
					this._SoTienCanTra = value;
					this.SendPropertyChanged("SoTienCanTra");
					this.OnSoTienCanTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VIP_CONGTACVIEN", Storage="_CONGTACVIENs", ThisKey="LevelVip", OtherKey="LevelVip")]
		public EntitySet<CONGTACVIEN> CONGTACVIENs
		{
			get
			{
				return this._CONGTACVIENs;
			}
			set
			{
				this._CONGTACVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGTACVIENs(CONGTACVIEN entity)
		{
			this.SendPropertyChanging();
			entity.VIP = this;
		}
		
		private void detach_CONGTACVIENs(CONGTACVIEN entity)
		{
			this.SendPropertyChanging();
			entity.VIP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAIDAT")]
	public partial class CAIDAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CaiDat;
		
		private string _TenThamSo;
		
		private string _HienThi;
		
		private string _GiaTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CaiDatChanging(int value);
    partial void OnID_CaiDatChanged();
    partial void OnTenThamSoChanging(string value);
    partial void OnTenThamSoChanged();
    partial void OnHienThiChanging(string value);
    partial void OnHienThiChanged();
    partial void OnGiaTriChanging(string value);
    partial void OnGiaTriChanged();
    #endregion
		
		public CAIDAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CaiDat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CaiDat
		{
			get
			{
				return this._ID_CaiDat;
			}
			set
			{
				if ((this._ID_CaiDat != value))
				{
					this.OnID_CaiDatChanging(value);
					this.SendPropertyChanging();
					this._ID_CaiDat = value;
					this.SendPropertyChanged("ID_CaiDat");
					this.OnID_CaiDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThamSo", DbType="VarChar(30)")]
		public string TenThamSo
		{
			get
			{
				return this._TenThamSo;
			}
			set
			{
				if ((this._TenThamSo != value))
				{
					this.OnTenThamSoChanging(value);
					this.SendPropertyChanging();
					this._TenThamSo = value;
					this.SendPropertyChanged("TenThamSo");
					this.OnTenThamSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienThi", DbType="NVarChar(50)")]
		public string HienThi
		{
			get
			{
				return this._HienThi;
			}
			set
			{
				if ((this._HienThi != value))
				{
					this.OnHienThiChanging(value);
					this.SendPropertyChanging();
					this._HienThi = value;
					this.SendPropertyChanged("HienThi");
					this.OnHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="VarChar(30)")]
		public string GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHIECKHAU")]
	public partial class CHIECKHAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ChiecKhau;
		
		private System.Nullable<double> _GiaTriCK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ChiecKhauChanging(int value);
    partial void OnID_ChiecKhauChanged();
    partial void OnGiaTriCKChanging(System.Nullable<double> value);
    partial void OnGiaTriCKChanged();
    #endregion
		
		public CHIECKHAU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ChiecKhau", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ChiecKhau
		{
			get
			{
				return this._ID_ChiecKhau;
			}
			set
			{
				if ((this._ID_ChiecKhau != value))
				{
					this.OnID_ChiecKhauChanging(value);
					this.SendPropertyChanging();
					this._ID_ChiecKhau = value;
					this.SendPropertyChanged("ID_ChiecKhau");
					this.OnID_ChiecKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriCK", DbType="Float")]
		public System.Nullable<double> GiaTriCK
		{
			get
			{
				return this._GiaTriCK;
			}
			set
			{
				if ((this._GiaTriCK != value))
				{
					this.OnGiaTriCKChanging(value);
					this.SendPropertyChanging();
					this._GiaTriCK = value;
					this.SendPropertyChanged("GiaTriCK");
					this.OnGiaTriCKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGTACVIEN")]
	public partial class CONGTACVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK_CTV;
		
		private string _TenTK_CTV;
		
		private string _MatKhau_CTV;
		
		private string _HoTen;
		
		private string _CMND;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<int> _LevelVip;
		
		private System.Nullable<decimal> _TienVip;
		
		private System.Nullable<System.DateTime> _NgayHetHanVip;
		
		private EntitySet<MONAN> _MONANs;
		
		private EntityRef<DOANHTHU> _DOANHTHU;
		
		private EntityRef<VIP> _VIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTK_CTVChanging(int value);
    partial void OnMaTK_CTVChanged();
    partial void OnTenTK_CTVChanging(string value);
    partial void OnTenTK_CTVChanged();
    partial void OnMatKhau_CTVChanging(string value);
    partial void OnMatKhau_CTVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnLevelVipChanging(System.Nullable<int> value);
    partial void OnLevelVipChanged();
    partial void OnTienVipChanging(System.Nullable<decimal> value);
    partial void OnTienVipChanged();
    partial void OnNgayHetHanVipChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanVipChanged();
    #endregion
		
		public CONGTACVIEN()
		{
			this._MONANs = new EntitySet<MONAN>(new Action<MONAN>(this.attach_MONANs), new Action<MONAN>(this.detach_MONANs));
			this._DOANHTHU = default(EntityRef<DOANHTHU>);
			this._VIP = default(EntityRef<VIP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_CTV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTK_CTV
		{
			get
			{
				return this._MaTK_CTV;
			}
			set
			{
				if ((this._MaTK_CTV != value))
				{
					this.OnMaTK_CTVChanging(value);
					this.SendPropertyChanging();
					this._MaTK_CTV = value;
					this.SendPropertyChanged("MaTK_CTV");
					this.OnMaTK_CTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK_CTV", DbType="VarChar(30)")]
		public string TenTK_CTV
		{
			get
			{
				return this._TenTK_CTV;
			}
			set
			{
				if ((this._TenTK_CTV != value))
				{
					this.OnTenTK_CTVChanging(value);
					this.SendPropertyChanging();
					this._TenTK_CTV = value;
					this.SendPropertyChanged("TenTK_CTV");
					this.OnTenTK_CTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau_CTV", DbType="VarChar(30)")]
		public string MatKhau_CTV
		{
			get
			{
				return this._MatKhau_CTV;
			}
			set
			{
				if ((this._MatKhau_CTV != value))
				{
					this.OnMatKhau_CTVChanging(value);
					this.SendPropertyChanging();
					this._MatKhau_CTV = value;
					this.SendPropertyChanged("MatKhau_CTV");
					this.OnMatKhau_CTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelVip", DbType="Int")]
		public System.Nullable<int> LevelVip
		{
			get
			{
				return this._LevelVip;
			}
			set
			{
				if ((this._LevelVip != value))
				{
					if (this._VIP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLevelVipChanging(value);
					this.SendPropertyChanging();
					this._LevelVip = value;
					this.SendPropertyChanged("LevelVip");
					this.OnLevelVipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienVip", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> TienVip
		{
			get
			{
				return this._TienVip;
			}
			set
			{
				if ((this._TienVip != value))
				{
					this.OnTienVipChanging(value);
					this.SendPropertyChanging();
					this._TienVip = value;
					this.SendPropertyChanged("TienVip");
					this.OnTienVipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanVip", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanVip
		{
			get
			{
				return this._NgayHetHanVip;
			}
			set
			{
				if ((this._NgayHetHanVip != value))
				{
					this.OnNgayHetHanVipChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanVip = value;
					this.SendPropertyChanged("NgayHetHanVip");
					this.OnNgayHetHanVipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTACVIEN_MONAN", Storage="_MONANs", ThisKey="MaTK_CTV", OtherKey="MaTK_CTV")]
		public EntitySet<MONAN> MONANs
		{
			get
			{
				return this._MONANs;
			}
			set
			{
				this._MONANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTACVIEN_DOANHTHU", Storage="_DOANHTHU", ThisKey="MaTK_CTV", OtherKey="MaTK_CTV", IsUnique=true, IsForeignKey=false)]
		public DOANHTHU DOANHTHU
		{
			get
			{
				return this._DOANHTHU.Entity;
			}
			set
			{
				DOANHTHU previousValue = this._DOANHTHU.Entity;
				if (((previousValue != value) 
							|| (this._DOANHTHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANHTHU.Entity = null;
						previousValue.CONGTACVIEN = null;
					}
					this._DOANHTHU.Entity = value;
					if ((value != null))
					{
						value.CONGTACVIEN = this;
					}
					this.SendPropertyChanged("DOANHTHU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VIP_CONGTACVIEN", Storage="_VIP", ThisKey="LevelVip", OtherKey="LevelVip", IsForeignKey=true)]
		public VIP VIP
		{
			get
			{
				return this._VIP.Entity;
			}
			set
			{
				VIP previousValue = this._VIP.Entity;
				if (((previousValue != value) 
							|| (this._VIP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VIP.Entity = null;
						previousValue.CONGTACVIENs.Remove(this);
					}
					this._VIP.Entity = value;
					if ((value != null))
					{
						value.CONGTACVIENs.Add(this);
						this._LevelVip = value.LevelVip;
					}
					else
					{
						this._LevelVip = default(Nullable<int>);
					}
					this.SendPropertyChanged("VIP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.CONGTACVIEN = this;
		}
		
		private void detach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.CONGTACVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATHANG")]
	public partial class DATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DatHang;
		
		private System.Nullable<int> _MaTK_User;
		
		private System.Nullable<System.DateTime> _ThoiGianDatHang;
		
		private string _DiaChiGiaoHang;
		
		private System.Nullable<bool> _TinhTrangGiao;
		
		private System.Nullable<bool> _DaThanhToan;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntitySet<DONHANG> _DONHANGs;
		
		private EntityRef<NGUOIDUNG> _NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DatHangChanging(int value);
    partial void OnID_DatHangChanged();
    partial void OnMaTK_UserChanging(System.Nullable<int> value);
    partial void OnMaTK_UserChanged();
    partial void OnThoiGianDatHangChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDatHangChanged();
    partial void OnDiaChiGiaoHangChanging(string value);
    partial void OnDiaChiGiaoHangChanged();
    partial void OnTinhTrangGiaoChanging(System.Nullable<bool> value);
    partial void OnTinhTrangGiaoChanged();
    partial void OnDaThanhToanChanging(System.Nullable<bool> value);
    partial void OnDaThanhToanChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public DATHANG()
		{
			this._DONHANGs = new EntitySet<DONHANG>(new Action<DONHANG>(this.attach_DONHANGs), new Action<DONHANG>(this.detach_DONHANGs));
			this._NGUOIDUNG = default(EntityRef<NGUOIDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DatHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DatHang
		{
			get
			{
				return this._ID_DatHang;
			}
			set
			{
				if ((this._ID_DatHang != value))
				{
					this.OnID_DatHangChanging(value);
					this.SendPropertyChanging();
					this._ID_DatHang = value;
					this.SendPropertyChanged("ID_DatHang");
					this.OnID_DatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_User", DbType="Int")]
		public System.Nullable<int> MaTK_User
		{
			get
			{
				return this._MaTK_User;
			}
			set
			{
				if ((this._MaTK_User != value))
				{
					if (this._NGUOIDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTK_UserChanging(value);
					this.SendPropertyChanging();
					this._MaTK_User = value;
					this.SendPropertyChanged("MaTK_User");
					this.OnMaTK_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDatHang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDatHang
		{
			get
			{
				return this._ThoiGianDatHang;
			}
			set
			{
				if ((this._ThoiGianDatHang != value))
				{
					this.OnThoiGianDatHangChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDatHang = value;
					this.SendPropertyChanged("ThoiGianDatHang");
					this.OnThoiGianDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGiaoHang", DbType="NVarChar(100)")]
		public string DiaChiGiaoHang
		{
			get
			{
				return this._DiaChiGiaoHang;
			}
			set
			{
				if ((this._DiaChiGiaoHang != value))
				{
					this.OnDiaChiGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiGiaoHang = value;
					this.SendPropertyChanged("DiaChiGiaoHang");
					this.OnDiaChiGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangGiao", DbType="Bit")]
		public System.Nullable<bool> TinhTrangGiao
		{
			get
			{
				return this._TinhTrangGiao;
			}
			set
			{
				if ((this._TinhTrangGiao != value))
				{
					this.OnTinhTrangGiaoChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangGiao = value;
					this.SendPropertyChanged("TinhTrangGiao");
					this.OnTinhTrangGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaThanhToan", DbType="Bit")]
		public System.Nullable<bool> DaThanhToan
		{
			get
			{
				return this._DaThanhToan;
			}
			set
			{
				if ((this._DaThanhToan != value))
				{
					this.OnDaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DaThanhToan = value;
					this.SendPropertyChanged("DaThanhToan");
					this.OnDaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATHANG_DONHANG", Storage="_DONHANGs", ThisKey="ID_DatHang", OtherKey="ID_DatHang")]
		public EntitySet<DONHANG> DONHANGs
		{
			get
			{
				return this._DONHANGs;
			}
			set
			{
				this._DONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_DATHANG", Storage="_NGUOIDUNG", ThisKey="MaTK_User", OtherKey="MaTK_User", IsForeignKey=true)]
		public NGUOIDUNG NGUOIDUNG
		{
			get
			{
				return this._NGUOIDUNG.Entity;
			}
			set
			{
				NGUOIDUNG previousValue = this._NGUOIDUNG.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDUNG.Entity = null;
						previousValue.DATHANGs.Remove(this);
					}
					this._NGUOIDUNG.Entity = value;
					if ((value != null))
					{
						value.DATHANGs.Add(this);
						this._MaTK_User = value.MaTK_User;
					}
					else
					{
						this._MaTK_User = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGUOIDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DATHANG = this;
		}
		
		private void detach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANG")]
	public partial class DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DatHang;
		
		private int _ID_MonAn;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<DATHANG> _DATHANG;
		
		private EntityRef<MONAN> _MONAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DatHangChanging(int value);
    partial void OnID_DatHangChanged();
    partial void OnID_MonAnChanging(int value);
    partial void OnID_MonAnChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public DONHANG()
		{
			this._DATHANG = default(EntityRef<DATHANG>);
			this._MONAN = default(EntityRef<MONAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DatHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DatHang
		{
			get
			{
				return this._ID_DatHang;
			}
			set
			{
				if ((this._ID_DatHang != value))
				{
					if (this._DATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DatHangChanging(value);
					this.SendPropertyChanging();
					this._ID_DatHang = value;
					this.SendPropertyChanged("ID_DatHang");
					this.OnID_DatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MonAn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_MonAn
		{
			get
			{
				return this._ID_MonAn;
			}
			set
			{
				if ((this._ID_MonAn != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MonAnChanging(value);
					this.SendPropertyChanging();
					this._ID_MonAn = value;
					this.SendPropertyChanged("ID_MonAn");
					this.OnID_MonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DATHANG_DONHANG", Storage="_DATHANG", ThisKey="ID_DatHang", OtherKey="ID_DatHang", IsForeignKey=true)]
		public DATHANG DATHANG
		{
			get
			{
				return this._DATHANG.Entity;
			}
			set
			{
				DATHANG previousValue = this._DATHANG.Entity;
				if (((previousValue != value) 
							|| (this._DATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DATHANG.Entity = null;
						previousValue.DONHANGs.Remove(this);
					}
					this._DATHANG.Entity = value;
					if ((value != null))
					{
						value.DONHANGs.Add(this);
						this._ID_DatHang = value.ID_DatHang;
					}
					else
					{
						this._ID_DatHang = default(int);
					}
					this.SendPropertyChanged("DATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_DONHANG", Storage="_MONAN", ThisKey="ID_MonAn", OtherKey="ID_MonAn", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.DONHANGs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.DONHANGs.Add(this);
						this._ID_MonAn = value.ID_MonAn;
					}
					else
					{
						this._ID_MonAn = default(int);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUVUC")]
	public partial class KHUVUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_KhuVuc;
		
		private string _TenKhuVuc;
		
		private EntitySet<MONAN> _MONANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KhuVucChanging(int value);
    partial void OnID_KhuVucChanged();
    partial void OnTenKhuVucChanging(string value);
    partial void OnTenKhuVucChanged();
    #endregion
		
		public KHUVUC()
		{
			this._MONANs = new EntitySet<MONAN>(new Action<MONAN>(this.attach_MONANs), new Action<MONAN>(this.detach_MONANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhuVuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_KhuVuc
		{
			get
			{
				return this._ID_KhuVuc;
			}
			set
			{
				if ((this._ID_KhuVuc != value))
				{
					this.OnID_KhuVucChanging(value);
					this.SendPropertyChanging();
					this._ID_KhuVuc = value;
					this.SendPropertyChanged("ID_KhuVuc");
					this.OnID_KhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuVuc", DbType="NVarChar(50)")]
		public string TenKhuVuc
		{
			get
			{
				return this._TenKhuVuc;
			}
			set
			{
				if ((this._TenKhuVuc != value))
				{
					this.OnTenKhuVucChanging(value);
					this.SendPropertyChanging();
					this._TenKhuVuc = value;
					this.SendPropertyChanged("TenKhuVuc");
					this.OnTenKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_MONAN", Storage="_MONANs", ThisKey="ID_KhuVuc", OtherKey="ID_KhuVuc")]
		public EntitySet<MONAN> MONANs
		{
			get
			{
				return this._MONANs;
			}
			set
			{
				this._MONANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = this;
		}
		
		private void detach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.KHUVUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MonAn;
		
		private System.Nullable<double> _GiamGia;
		
		private EntityRef<MONAN> _MONAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MonAnChanging(int value);
    partial void OnID_MonAnChanged();
    partial void OnGiamGiaChanging(System.Nullable<double> value);
    partial void OnGiamGiaChanged();
    #endregion
		
		public KhuyenMai()
		{
			this._MONAN = default(EntityRef<MONAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MonAn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_MonAn
		{
			get
			{
				return this._ID_MonAn;
			}
			set
			{
				if ((this._ID_MonAn != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MonAnChanging(value);
					this.SendPropertyChanging();
					this._ID_MonAn = value;
					this.SendPropertyChanged("ID_MonAn");
					this.OnID_MonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Float")]
		public System.Nullable<double> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_KhuyenMai", Storage="_MONAN", ThisKey="ID_MonAn", OtherKey="ID_MonAn", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.KhuyenMai = null;
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.KhuyenMai = this;
						this._ID_MonAn = value.ID_MonAn;
					}
					else
					{
						this._ID_MonAn = default(int);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBUAAN")]
	public partial class LOAIBUAAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Loai;
		
		private string _TenLoai;
		
		private EntitySet<MONAN> _MONANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LoaiChanging(int value);
    partial void OnID_LoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LOAIBUAAN()
		{
			this._MONANs = new EntitySet<MONAN>(new Action<MONAN>(this.attach_MONANs), new Action<MONAN>(this.detach_MONANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Loai
		{
			get
			{
				return this._ID_Loai;
			}
			set
			{
				if ((this._ID_Loai != value))
				{
					this.OnID_LoaiChanging(value);
					this.SendPropertyChanging();
					this._ID_Loai = value;
					this.SendPropertyChanged("ID_Loai");
					this.OnID_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBUAAN_MONAN", Storage="_MONANs", ThisKey="ID_Loai", OtherKey="ID_Loai")]
		public EntitySet<MONAN> MONANs
		{
			get
			{
				return this._MONANs;
			}
			set
			{
				this._MONANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBUAAN = this;
		}
		
		private void detach_MONANs(MONAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBUAAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONAN")]
	public partial class MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MonAn;
		
		private string _TenMonAn;
		
		private System.Nullable<decimal> _GiaBan;
		
		private string _MoTa;
		
		private string _AnhBia;
		
		private System.Nullable<System.DateTime> _NgayCapNhap;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _PhiVanChuyen;
		
		private System.Nullable<int> _ID_KhuVuc;
		
		private System.Nullable<int> _ID_Loai;
		
		private System.Nullable<int> _MaTK_CTV;
		
		private EntitySet<DONHANG> _DONHANGs;
		
		private EntityRef<KhuyenMai> _KhuyenMai;
		
		private EntityRef<CONGTACVIEN> _CONGTACVIEN;
		
		private EntityRef<KHUVUC> _KHUVUC;
		
		private EntityRef<LOAIBUAAN> _LOAIBUAAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MonAnChanging(int value);
    partial void OnID_MonAnChanged();
    partial void OnTenMonAnChanging(string value);
    partial void OnTenMonAnChanged();
    partial void OnGiaBanChanging(System.Nullable<decimal> value);
    partial void OnGiaBanChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnNgayCapNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhapChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnPhiVanChuyenChanging(System.Nullable<decimal> value);
    partial void OnPhiVanChuyenChanged();
    partial void OnID_KhuVucChanging(System.Nullable<int> value);
    partial void OnID_KhuVucChanged();
    partial void OnID_LoaiChanging(System.Nullable<int> value);
    partial void OnID_LoaiChanged();
    partial void OnMaTK_CTVChanging(System.Nullable<int> value);
    partial void OnMaTK_CTVChanged();
    #endregion
		
		public MONAN()
		{
			this._DONHANGs = new EntitySet<DONHANG>(new Action<DONHANG>(this.attach_DONHANGs), new Action<DONHANG>(this.detach_DONHANGs));
			this._KhuyenMai = default(EntityRef<KhuyenMai>);
			this._CONGTACVIEN = default(EntityRef<CONGTACVIEN>);
			this._KHUVUC = default(EntityRef<KHUVUC>);
			this._LOAIBUAAN = default(EntityRef<LOAIBUAAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MonAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_MonAn
		{
			get
			{
				return this._ID_MonAn;
			}
			set
			{
				if ((this._ID_MonAn != value))
				{
					this.OnID_MonAnChanging(value);
					this.SendPropertyChanging();
					this._ID_MonAn = value;
					this.SendPropertyChanged("ID_MonAn");
					this.OnID_MonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonAn", DbType="NVarChar(100)")]
		public string TenMonAn
		{
			get
			{
				return this._TenMonAn;
			}
			set
			{
				if ((this._TenMonAn != value))
				{
					this.OnTenMonAnChanging(value);
					this.SendPropertyChanging();
					this._TenMonAn = value;
					this.SendPropertyChanged("TenMonAn");
					this.OnTenMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(100)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhap
		{
			get
			{
				return this._NgayCapNhap;
			}
			set
			{
				if ((this._NgayCapNhap != value))
				{
					this.OnNgayCapNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhap = value;
					this.SendPropertyChanged("NgayCapNhap");
					this.OnNgayCapNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiVanChuyen", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> PhiVanChuyen
		{
			get
			{
				return this._PhiVanChuyen;
			}
			set
			{
				if ((this._PhiVanChuyen != value))
				{
					this.OnPhiVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._PhiVanChuyen = value;
					this.SendPropertyChanged("PhiVanChuyen");
					this.OnPhiVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhuVuc", DbType="Int")]
		public System.Nullable<int> ID_KhuVuc
		{
			get
			{
				return this._ID_KhuVuc;
			}
			set
			{
				if ((this._ID_KhuVuc != value))
				{
					if (this._KHUVUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhuVucChanging(value);
					this.SendPropertyChanging();
					this._ID_KhuVuc = value;
					this.SendPropertyChanged("ID_KhuVuc");
					this.OnID_KhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Loai", DbType="Int")]
		public System.Nullable<int> ID_Loai
		{
			get
			{
				return this._ID_Loai;
			}
			set
			{
				if ((this._ID_Loai != value))
				{
					if (this._LOAIBUAAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LoaiChanging(value);
					this.SendPropertyChanging();
					this._ID_Loai = value;
					this.SendPropertyChanged("ID_Loai");
					this.OnID_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_CTV", DbType="Int")]
		public System.Nullable<int> MaTK_CTV
		{
			get
			{
				return this._MaTK_CTV;
			}
			set
			{
				if ((this._MaTK_CTV != value))
				{
					if (this._CONGTACVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTK_CTVChanging(value);
					this.SendPropertyChanging();
					this._MaTK_CTV = value;
					this.SendPropertyChanged("MaTK_CTV");
					this.OnMaTK_CTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_DONHANG", Storage="_DONHANGs", ThisKey="ID_MonAn", OtherKey="ID_MonAn")]
		public EntitySet<DONHANG> DONHANGs
		{
			get
			{
				return this._DONHANGs;
			}
			set
			{
				this._DONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_KhuyenMai", Storage="_KhuyenMai", ThisKey="ID_MonAn", OtherKey="ID_MonAn", IsUnique=true, IsForeignKey=false)]
		public KhuyenMai KhuyenMai
		{
			get
			{
				return this._KhuyenMai.Entity;
			}
			set
			{
				KhuyenMai previousValue = this._KhuyenMai.Entity;
				if (((previousValue != value) 
							|| (this._KhuyenMai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuyenMai.Entity = null;
						previousValue.MONAN = null;
					}
					this._KhuyenMai.Entity = value;
					if ((value != null))
					{
						value.MONAN = this;
					}
					this.SendPropertyChanged("KhuyenMai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTACVIEN_MONAN", Storage="_CONGTACVIEN", ThisKey="MaTK_CTV", OtherKey="MaTK_CTV", IsForeignKey=true)]
		public CONGTACVIEN CONGTACVIEN
		{
			get
			{
				return this._CONGTACVIEN.Entity;
			}
			set
			{
				CONGTACVIEN previousValue = this._CONGTACVIEN.Entity;
				if (((previousValue != value) 
							|| (this._CONGTACVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGTACVIEN.Entity = null;
						previousValue.MONANs.Remove(this);
					}
					this._CONGTACVIEN.Entity = value;
					if ((value != null))
					{
						value.MONANs.Add(this);
						this._MaTK_CTV = value.MaTK_CTV;
					}
					else
					{
						this._MaTK_CTV = default(Nullable<int>);
					}
					this.SendPropertyChanged("CONGTACVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHUVUC_MONAN", Storage="_KHUVUC", ThisKey="ID_KhuVuc", OtherKey="ID_KhuVuc", IsForeignKey=true)]
		public KHUVUC KHUVUC
		{
			get
			{
				return this._KHUVUC.Entity;
			}
			set
			{
				KHUVUC previousValue = this._KHUVUC.Entity;
				if (((previousValue != value) 
							|| (this._KHUVUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHUVUC.Entity = null;
						previousValue.MONANs.Remove(this);
					}
					this._KHUVUC.Entity = value;
					if ((value != null))
					{
						value.MONANs.Add(this);
						this._ID_KhuVuc = value.ID_KhuVuc;
					}
					else
					{
						this._ID_KhuVuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHUVUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBUAAN_MONAN", Storage="_LOAIBUAAN", ThisKey="ID_Loai", OtherKey="ID_Loai", IsForeignKey=true)]
		public LOAIBUAAN LOAIBUAAN
		{
			get
			{
				return this._LOAIBUAAN.Entity;
			}
			set
			{
				LOAIBUAAN previousValue = this._LOAIBUAAN.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBUAAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBUAAN.Entity = null;
						previousValue.MONANs.Remove(this);
					}
					this._LOAIBUAAN.Entity = value;
					if ((value != null))
					{
						value.MONANs.Add(this);
						this._ID_Loai = value.ID_Loai;
					}
					else
					{
						this._ID_Loai = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIBUAAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK_User;
		
		private string _TenTK_User;
		
		private string _MatKhau_User;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private EntitySet<DATHANG> _DATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTK_UserChanging(int value);
    partial void OnMaTK_UserChanged();
    partial void OnTenTK_UserChanging(string value);
    partial void OnTenTK_UserChanged();
    partial void OnMatKhau_UserChanging(string value);
    partial void OnMatKhau_UserChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			this._DATHANGs = new EntitySet<DATHANG>(new Action<DATHANG>(this.attach_DATHANGs), new Action<DATHANG>(this.detach_DATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_User", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTK_User
		{
			get
			{
				return this._MaTK_User;
			}
			set
			{
				if ((this._MaTK_User != value))
				{
					this.OnMaTK_UserChanging(value);
					this.SendPropertyChanging();
					this._MaTK_User = value;
					this.SendPropertyChanged("MaTK_User");
					this.OnMaTK_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK_User", DbType="VarChar(30)")]
		public string TenTK_User
		{
			get
			{
				return this._TenTK_User;
			}
			set
			{
				if ((this._TenTK_User != value))
				{
					this.OnTenTK_UserChanging(value);
					this.SendPropertyChanging();
					this._TenTK_User = value;
					this.SendPropertyChanged("TenTK_User");
					this.OnTenTK_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau_User", DbType="VarChar(30)")]
		public string MatKhau_User
		{
			get
			{
				return this._MatKhau_User;
			}
			set
			{
				if ((this._MatKhau_User != value))
				{
					this.OnMatKhau_UserChanging(value);
					this.SendPropertyChanging();
					this._MatKhau_User = value;
					this.SendPropertyChanged("MatKhau_User");
					this.OnMatKhau_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDUNG_DATHANG", Storage="_DATHANGs", ThisKey="MaTK_User", OtherKey="MaTK_User")]
		public EntitySet<DATHANG> DATHANGs
		{
			get
			{
				return this._DATHANGs;
			}
			set
			{
				this._DATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATHANGs(DATHANG entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = this;
		}
		
		private void detach_DATHANGs(DATHANG entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Top5MonAn")]
	public partial class V_Top5MonAn
	{
		
		private string _TenMonAn;
		
		private System.Nullable<int> _MaTK_CTV;
		
		private System.Nullable<int> _Số_lượng;
		
		public V_Top5MonAn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonAn", DbType="NVarChar(100)")]
		public string TenMonAn
		{
			get
			{
				return this._TenMonAn;
			}
			set
			{
				if ((this._TenMonAn != value))
				{
					this._TenMonAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_CTV", DbType="Int")]
		public System.Nullable<int> MaTK_CTV
		{
			get
			{
				return this._MaTK_CTV;
			}
			set
			{
				if ((this._MaTK_CTV != value))
				{
					this._MaTK_CTV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số lượng]", Storage="_Số_lượng", DbType="Int")]
		public System.Nullable<int> Số_lượng
		{
			get
			{
				return this._Số_lượng;
			}
			set
			{
				if ((this._Số_lượng != value))
				{
					this._Số_lượng = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Top5KhachHang")]
	public partial class V_Top5KhachHang
	{
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private System.Nullable<int> _MaTK_CTV;
		
		private System.Nullable<decimal> _Tổng_tiền;
		
		public V_Top5KhachHang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_CTV", DbType="Int")]
		public System.Nullable<int> MaTK_CTV
		{
			get
			{
				return this._MaTK_CTV;
			}
			set
			{
				if ((this._MaTK_CTV != value))
				{
					this._MaTK_CTV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tổng tiền]", Storage="_Tổng_tiền", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Tổng_tiền
		{
			get
			{
				return this._Tổng_tiền;
			}
			set
			{
				if ((this._Tổng_tiền != value))
				{
					this._Tổng_tiền = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOANHTHU")]
	public partial class DOANHTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTK_CTV;
		
		private System.Nullable<decimal> _TongDoanhThu;
		
		private System.Nullable<decimal> _TienChiecKhau;
		
		private System.Nullable<System.DateTime> _Thang;
		
		private EntityRef<CONGTACVIEN> _CONGTACVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTK_CTVChanging(int value);
    partial void OnMaTK_CTVChanged();
    partial void OnTongDoanhThuChanging(System.Nullable<decimal> value);
    partial void OnTongDoanhThuChanged();
    partial void OnTienChiecKhauChanging(System.Nullable<decimal> value);
    partial void OnTienChiecKhauChanged();
    partial void OnThangChanging(System.Nullable<System.DateTime> value);
    partial void OnThangChanged();
    #endregion
		
		public DOANHTHU()
		{
			this._CONGTACVIEN = default(EntityRef<CONGTACVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK_CTV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTK_CTV
		{
			get
			{
				return this._MaTK_CTV;
			}
			set
			{
				if ((this._MaTK_CTV != value))
				{
					if (this._CONGTACVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTK_CTVChanging(value);
					this.SendPropertyChanging();
					this._MaTK_CTV = value;
					this.SendPropertyChanged("MaTK_CTV");
					this.OnMaTK_CTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this.OnTongDoanhThuChanging(value);
					this.SendPropertyChanging();
					this._TongDoanhThu = value;
					this.SendPropertyChanged("TongDoanhThu");
					this.OnTongDoanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienChiecKhau", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> TienChiecKhau
		{
			get
			{
				return this._TienChiecKhau;
			}
			set
			{
				if ((this._TienChiecKhau != value))
				{
					this.OnTienChiecKhauChanging(value);
					this.SendPropertyChanging();
					this._TienChiecKhau = value;
					this.SendPropertyChanged("TienChiecKhau");
					this.OnTienChiecKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTACVIEN_DOANHTHU", Storage="_CONGTACVIEN", ThisKey="MaTK_CTV", OtherKey="MaTK_CTV", IsForeignKey=true)]
		public CONGTACVIEN CONGTACVIEN
		{
			get
			{
				return this._CONGTACVIEN.Entity;
			}
			set
			{
				CONGTACVIEN previousValue = this._CONGTACVIEN.Entity;
				if (((previousValue != value) 
							|| (this._CONGTACVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGTACVIEN.Entity = null;
						previousValue.DOANHTHU = null;
					}
					this._CONGTACVIEN.Entity = value;
					if ((value != null))
					{
						value.DOANHTHU = this;
						this._MaTK_CTV = value.MaTK_CTV;
					}
					else
					{
						this._MaTK_CTV = default(int);
					}
					this.SendPropertyChanged("CONGTACVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
